// ─── ICON LIBRARY ───
export const ICON_LIBRARY = [
  { group: "Negócios", icons: ["🤝", "💰", "📈", "💼", "🏢", "🎯", "💡", "🔑", "📋", "🏆", "💎", "🪙"] },
  { group: "Marketing", icons: ["📱", "📣", "🎨", "✍️", "📢", "🧲", "🔥", "⚡", "🚀", "💬", "🗣️", "📩"] },
  { group: "Conteúdo", icons: ["📄", "📝", "✅", "📊", "📐", "🗂️", "📚", "🎬", "🎙️", "📸", "🖼️", "🔗"] },
  { group: "Pilates", icons: ["🧘", "💪", "🏋️", "🤸", "🧠", "❤️", "🩺", "🦴", "🏃", "⚕️", "🌿", "✨"] },
  { group: "Hashtags", icons: ["#️⃣", "🏷️", "📌", "🔖", "⭐", "🌟", "💫", "🎖️", "🥇", "🎁", "🎉", "🔔"] },
];

export const DEFAULT_CONFIG = {
  brandName: "VOLL PILATES GROUP", brandTag: "by Rafael Voll",
  landingSubtitle: "Materiais exclusivos para turbinar\nseus resultados no Pilates",
  landingStat1Label: "Materiais", landingStat2: "Grátis", landingStat2Label: "Para começar",
  landingStat3: "100%", landingStat3Label: "Prático",
  nameLabel: "Seu nome", namePlaceholder: "Como posso te chamar?",
  whatsLabel: "Seu WhatsApp", whatsPlaceholder: "(00) 00000-0000",
  ctaText: "Acessar materiais →", safeText: "🔒 Seus dados estão seguros.",
  hubGreetPrefix: "Olá,", hubGreetEmoji: "👋", hubSubtitle: "VOLL Pilates Hub",
  progressSuffix: "materiais baixados",
  progressHint: "Desbloqueie mais indicando amigos ou engajando nos posts!",
  profilePromptText: "Ganhe créditos!",
  profileSectionTitle: "Ganhe créditos",
  sectionTitle: "Materiais disponíveis",
  ctaBannerTitle: "Quer acesso a tudo?", ctaBannerDesc: "Todos os materiais + conteúdos exclusivos", ctaBannerBtn: "Em breve",
  ctaBannerBadge: "Curso completo",
  socialProofMode: "downloads",
  socialProofNames: ["Maria", "João", "Ana", "Pedro", "Carla", "Lucas", "Julia", "Rafael", "Camila", "Bruno"],
  socialProofMinutes: [3, 12, 25, 47, 68, 95, 120, 180, 240, 310],
  socialProofBoost: 150,
  bannerAllAccessPrice: 97,
  bannerAllAccessLink: "",
  bannerPersonalized: true,
  shareModalTitle: "Indique um amigo", shareModalDesc: "Indique um amigo para desbloquear. Quanto mais indica, mais conteúdo libera!",
  commentModalTitle: "Engaje no post", commentModalDesc: "Comente no post mais recente no Instagram e depois volte aqui!",
  surveyModalTitle: "Pesquisa Rápida",
  instagramUrl: "https://instagram.com/rafael.voll", instagramHandle: "@rafael.voll",
  baseUrl: "https://seuapp.com",
  logoUrl: "",
  profileEnabled: "true",
  bioPhotoUrl: "https://vollpilates.com.br/rafael/wp-content/uploads/2025/04/foto-rafa.webp",
  creditsEnabled: "true",
  creditsInitial: "3",
  creditsReferral: "2",
  creditsReferralMsg: "Oi! Conheça o Hub de Materiais Gratuitos de Pilates do Rafael Juliano. Tem e-books, guias e vídeos incríveis! Acesse: {link}",
  creditsTooltipTitle: "🎯 Seus créditos: {n}",
  creditsTooltipDesc: "Use créditos para desbloquear materiais exclusivos. Ganhe mais completando fases do seu perfil ou indicando amigas!",
  creditsTooltipBtn: "Ganhar créditos",
  creditsStoreTitle: "🎯 Ganhe Créditos",
  creditsStorePhaseSubtitle: "Responda sobre você",
  creditsStoreReferralTitle: "Indicar amigo",
  creditsStoreReferralSubtitle: "Envie pelo WhatsApp",
  creditsStoreCloseBtn: "Fechar",
  bioName: "RAFAEL JULIANO",
  bioLine1: "💼 Fundador | VOLL Pilates Group",
  bioLine2: "🎯 Marketing, Gestão e Vendas no Pilates",
  bioStat1: "+230", bioStat1Label: "Studios VOLL",
  bioStat2: "+85 mil", bioStat2Label: "Instrutores Formados",

  // ─── Mensagens e avisos (popups, banners, modais) ───
  messagesEmailPopupEnabled: "true",
  emailPopupTitle: "Informe agora o seu email e receba +2 créditos",
  emailPopupBtnSubmit: "Receber créditos",
  emailPopupBtnDismiss: "Agora não",

  messagesHowWorksAutoShow: "true",
  howWorksFooterLink: "Como funciona?",
  howWorksTitle: "💡 Como funciona?",
  howWorksStep1Title: "Materiais gratuitos",
  howWorksStep1Desc: "Baixe e-books, guias e templates feitos pra você crescer no Pilates.",
  howWorksStep2Title: "Créditos",
  howWorksStep2Desc: "Alguns materiais pedem créditos. Você já ganhou {n} ao se cadastrar!",
  howWorksStep3Title: "Ganhe mais",
  howWorksStep3Desc: "Complete seu perfil ou indique amigas para ganhar créditos extras.",

  messagesOnboardingEnabled: "true",
  onboardingWelcomeTitle: "Bem-vinda, {name}!",
  onboardingWelcomeDesc: "Aqui você encontra materiais gratuitos pra turbinar sua carreira no Pilates: e-books, guias, templates e mais.",
  onboardingCreditsTitle: "Créditos",
  onboardingCreditsDesc: "Alguns materiais especiais precisam de créditos pra desbloquear. Você já ganhou {n} créditos ao se cadastrar!",
  onboardingGanheTitle: "Ganhe mais créditos",
  onboardingGanheDesc: "Complete as fases do seu perfil ou indique amigas para ganhar créditos extras e desbloquear tudo!",
  onboardingNextBtn: "Próximo →",
  onboardingStartBtn: "Começar! 🚀",
  onboardingSkipBtn: "Pular",

  messagesInstallBannerEnabled: "true",
  installBannerTitle: "Instale o VOLL Hub na tela inicial — como um app",
  installBannerStepsIos1: "Toque em Compartilhar no Safari",
  installBannerStepsIos2: "Toque em \"Adicionar à Tela de Início\"",
  installBannerStepsIos3: "Confirme em \"Adicionar\"",
  installBannerStepsAndroid1: "Menu (⋮) no Chrome",
  installBannerStepsAndroid2: "\"Adicionar à tela inicial\" ou \"Instalar app\"",
  installBannerStepsAndroid3: "Confirme e pronto",
  installBannerBtnInstall: "Instalar agora",
  installBannerBtnDone: "Já instalei",
  installBannerBtnLater: "Agora não",

  messagesPhotoAnnounceEnabled: "true",
  photoAnnounceText: "Novidade: adicione sua foto no Perfil e apareça no ranking.",
  photoAnnounceBtnVer: "Ver",
  photoAnnounceBtnFechar: "Fechar",
};

export const DEFAULT_BIO_LINKS = [
  { id: "1", title: "Pós Internacional", subtitle: "Formação internacional em Pilates", icon: "🌎", imageUrl: "", url: "https://vollpilates.com.br/rafael/cta/pos-internacional", active: true, clicks: 0, highlight: true, badge: "🔥 NOVO", color: "linear-gradient(135deg, #1a3a30, #0d2920)" },
  { id: "2", title: "Encontro Pilates 2026", subtitle: "O maior evento de Pilates do Brasil", icon: "🎪", imageUrl: "", url: "https://encontropilates.com.br/", active: true, clicks: 0, highlight: true, badge: "⭐ IMPERDÍVEL", color: "linear-gradient(135deg, #2a1a3a, #1a0d29)" },
  { id: "3", title: "Pós Patologias e Biomecânica", subtitle: "Pós-graduação especializada", icon: "🧬", imageUrl: "", url: "https://materiais.vollpilates.com.br/pos-graduacao-pilates-para-patologias-e-biomecanica-aplicada-captacao", active: true, clicks: 0 },
  { id: "4", title: "Jornada Pilates 2026", subtitle: "Evento online e gratuito", icon: "🚀", imageUrl: "", url: "https://jornadapilates.com.br/2026", active: true, clicks: 0 },
  { id: "5", title: "Studio Blindado", subtitle: "Imersão em gestão de studio", icon: "🛡️", imageUrl: "", url: "https://vollpilates.com.br/imersaostudioblindado/", active: true, clicks: 0 },
  { id: "6", title: "Kit Documentos Jurídicos", subtitle: "Contratos e termos prontos", icon: "📋", imageUrl: "", url: "https://materiais.vollpilates.com.br/kit-juridico-pagina-de-venda", active: true, clicks: 0 },
  { id: "7", title: "Pilates Connect", subtitle: "Comunidade exclusiva", icon: "🤝", imageUrl: "", url: "https://vollpilates.com.br/rafael/cta/pilatesconnect", active: true, clicks: 0 },
  { id: "8", title: "Formação Clássica", subtitle: "Curso de Pilates Clássico", icon: "🏛️", imageUrl: "", url: "https://cursopilatesclassico.com.br/", active: true, clicks: 0 },
  { id: "9", title: "MBA VOLL", subtitle: "MBA em gestão de Pilates", icon: "🎓", imageUrl: "", url: "https://vollpilates.com.br/rafael/cta/mbavoll", active: true, clicks: 0 },
  { id: "10", title: "VOLL+", subtitle: "Plataforma de conteúdo", icon: "▶️", imageUrl: "", url: "https://vollpilates.com.br/rafael/cta/vollplus", active: true, clicks: 0 },
  { id: "11", title: "Franquias", subtitle: "Abra seu studio VOLL", icon: "🏢", imageUrl: "", url: "https://vollpilates.com.br/rafael/cta/franquiadepilates", active: true, clicks: 0 },
  { id: "12", title: "Dúvidas Cursos", subtitle: "Fale com nosso time", icon: "💬", imageUrl: "", url: "https://vollpilates.com.br/rafael/cta/duvidas-cursos", active: true, clicks: 0 },
  { id: "13", title: "Grupos Exclusivos", subtitle: "WhatsApp e Telegram", icon: "👥", imageUrl: "", url: "https://vollpilates.com.br/rafael/grupos-exclusivos/", active: true, clicks: 0 },
  { id: "hub", title: "Materiais Gratuitos", subtitle: "E-books, guias e vídeos exclusivos", icon: "🎁", imageUrl: "", url: "_hub", active: true, clicks: 0, highlight: true, badge: "GRÁTIS", color: "linear-gradient(135deg, #0d2920, #1a3a20)" },
];

export const PERM_LABELS = {
  materials_view: { label: "Ver materiais", icon: "📄", group: "Materiais" },
  materials_edit: { label: "Criar / editar / excluir", icon: "✏️", group: "Materiais" },
  leads_view: { label: "Ver leads", icon: "👥", group: "Leads" },
  leads_export: { label: "Exportar CSV / copiar números", icon: "📊", group: "Leads" },
  leads_whatsapp: { label: "Enviar WhatsApp", icon: "💬", group: "Leads" },
  textos_edit: { label: "Editar textos e configs", icon: "✏️", group: "CMS" },
  users_manage: { label: "Gerenciar usuários", icon: "🔐", group: "Sistema" },
};

export const THEMES = {
  dark: { bg: "#060a09", cardBg: "linear-gradient(180deg, #0d1512 0%, #080d0b 100%)", cardBorder: "#1a2e28", inputBg: "#080d0b", inputBorder: "#1a2e28", text: "#f0f0f0", textMuted: "#7a8d86", textFaint: "#4a5d56", accent: "#7DE2C7", accentDark: "#349980", gold: "#FFD863", badgeBg: "#111a17", badgeBorder: "#1e3029", progressTrack: "#152420", overlayBg: "rgba(0,0,0,0.8)", toastBg: "#0d1f1a", toastBorder: "#1a2e28", glowOp: 0.15, dlBg: "#0d2920", dlBorder: "#7DE2C744", statBg: "#0d1512", statBorder: "#1a2e28", tabBg: "#080d0b", tabBorder: "#152420", tabActiveBg: "#1a2e28", matIcon: "linear-gradient(135deg, #0d1f1a, #0a1a14)", matIconLock: "linear-gradient(135deg, #1a1a22, #141418)", ctaBanBg: "linear-gradient(135deg, #1a1a10, #0d1512)", ctaBanBrd: "#2e2e1a", placeholder: "#4a5450", focusRing: "#34998022", avBg: "linear-gradient(135deg, #0d1f1a, #0a1a14)", avBrd: "#1a2e28", shadow: "0 20px 60px rgba(0,0,0,0.6)", dangerBg: "#1a1210", dangerBrd: "#2e1a1a", dangerTxt: "#e87d7d", successBg: "#0d2920", newBg: "#1a1a10", newBorder: "#FFD86344", newText: "#FFD863", spotBg: "linear-gradient(135deg, #0d1f1a, #0a1610)", spotBorder: "#349980" },
  light: { bg: "#f4f7f6", cardBg: "linear-gradient(180deg, #ffffff 0%, #f8faf9 100%)", cardBorder: "#d4e5de", inputBg: "#f0f5f3", inputBorder: "#c8ddd5", text: "#1a2e28", textMuted: "#5a7a6e", textFaint: "#8aa89a", accent: "#349980", accentDark: "#1a7a60", gold: "#c49500", badgeBg: "#e8f5f0", badgeBorder: "#c8ddd5", progressTrack: "#d4e5de", overlayBg: "rgba(0,0,0,0.45)", toastBg: "#ffffff", toastBorder: "#d4e5de", glowOp: 0.08, dlBg: "#e0f5ed", dlBorder: "#7DE2C788", statBg: "#ffffff", statBorder: "#d4e5de", tabBg: "#e8f0ed", tabBorder: "#d4e5de", tabActiveBg: "#ffffff", matIcon: "linear-gradient(135deg, #e0f5ed, #d4ece3)", matIconLock: "linear-gradient(135deg, #e8e8ee, #dddde3)", ctaBanBg: "linear-gradient(135deg, #fdf8e8, #f4f7f6)", ctaBanBrd: "#e8ddb0", placeholder: "#8aa89a", focusRing: "#34998030", avBg: "linear-gradient(135deg, #e0f5ed, #d4ece3)", avBrd: "#c8ddd5", shadow: "0 20px 60px rgba(0,0,0,0.08)", dangerBg: "#fde8e8", dangerBrd: "#e8b0b0", dangerTxt: "#c44", successBg: "#e0f5ed", newBg: "#fdf8e8", newBorder: "#e8ddb044", newText: "#c49500", spotBg: "linear-gradient(135deg, #e0f5ed, #f0faf6)", spotBorder: "#349980" },
};
